./goldenupdate.sh actions_copypaste_basic -e
./goldenupdate.sh actions_copypaste_retainstyle -e
./goldenupdate.sh actions_editor_tag_nobackticks -e
./goldenupdate.sh actions_editor_tag_noblanktags -e
./goldenupdate.sh actions_editor_tag_nodupetags -e
./goldenupdate.sh actions_funnel_command_allowedchars -e
./goldenupdate.sh actions_funnel_command_childorsibling -e
./goldenupdate.sh actions_funnel_command_spaceafter -e
./goldenupdate.sh actions_funnel_command_tildeafter -e
./goldenupdate.sh actions_funnel_doc_basictyping -e
./goldenupdate.sh actions_funnel_doc_insertcodeobject -e
./goldenupdate.sh actions_funnel_doc_startwithsemi -e
./goldenupdate.sh actions_funnel_doc_tab -n
./goldenupdate.sh actions_funnel_doc_tab -e
./goldenupdate.sh actions_funnel_doc_tabinout -e
./goldenupdate.sh actions_funnel_doc_typedkey -e
./goldenupdate.sh actions_funnel_downarrowpastend -e
./goldenupdate.sh actions_funnel_emptylines -e
./goldenupdate.sh actions_funnel_integer_endwithzero -e
./goldenupdate.sh actions_funnel_integer_evaluate_incomplete -e
./goldenupdate.sh actions_funnel_integer_nomoreminuses -e
./goldenupdate.sh actions_funnel_integer_startnewletter -e
./goldenupdate.sh actions_funnel_integer_startswithzero -e
./goldenupdate.sh actions_funnel_integer_zeroswithnegatives -e
./goldenupdate.sh actions_funnel_joinwords -e
./goldenupdate.sh actions_funnel_lambda_basic -e
./goldenupdate.sh actions_funnel_letter_backspace -e
./goldenupdate.sh actions_funnel_letter_backspaceincommand -e
./goldenupdate.sh actions_funnel_longstring -e
./goldenupdate.sh actions_funnel_midseparatorlinebreak -e
./goldenupdate.sh actions_funnel_separator_appending -e
./goldenupdate.sh actions_funnel_separatorselect -e
./goldenupdate.sh actions_funnel_shortstring -e
./goldenupdate.sh actions_funnel_symbol_basicops -e
./goldenupdate.sh actions_funnel_uparrow -e
./goldenupdate.sh actions_funnel_uparrowpastend -e
./goldenupdate.sh actions_funnel_value_downuparrows -e
./goldenupdate.sh actions_funnel_word_arrows -e
./goldenupdate.sh actions_funnel_word_deletelastword -e
./goldenupdate.sh actions_funnel_word_insertionpoint -e
./goldenupdate.sh actions_funnel_word_leftarrow -e
./goldenupdate.sh actions_funnel_zlist_insert -e
./goldenupdate.sh actions_mouse_clickafterinsert -e
./goldenupdate.sh copy_bool -e
./goldenupdate.sh copy_closure -e
./goldenupdate.sh copy_command -e
./goldenupdate.sh copy_error -e
./goldenupdate.sh eventqueue_events_expectationfulfill -n
./goldenupdate.sh eventqueue_events_gc -n
./goldenupdate.sh eventqueue_events_importanttoplevelrender -n
./goldenupdate.sh eventqueue_events_rendernoderender -n
./goldenupdate.sh eventqueue_events_toplevelrender -n
./goldenupdate.sh eventqueue_priority_addedwhiledequeueing -n
./goldenupdate.sh eventqueue_priority_inverseordering -n
./goldenupdate.sh eventqueue_priority_inverseordering2 -n
./goldenupdate.sh eventqueue_priority_normalandimportantrender -n
./goldenupdate.sh execution_eval_andkeep_activateexpectation -e
./goldenupdate.sh execution_expectation_fulfill_externalresult_ffwith -e
./goldenupdate.sh execution_expectation_fulfill_ffclosure -e
./goldenupdate.sh execution_lambda_nestedlambda -e
./goldenupdate.sh execution_lambda_noargs -e
./goldenupdate.sh execution_lambda_twoargs -e
./goldenupdate.sh execution_literal_expectation -e
./goldenupdate.sh execution_literal_valuecopies -e
./goldenupdate.sh execution_normal_argeval_builtin_toomanyargs -e
./goldenupdate.sh execution_normal_replace -e
./goldenupdate.sh execution_org_dereference -e
./goldenupdate.sh execution_paramparser_anynumber -e
./goldenupdate.sh execution_paramparser_variadic -e
./goldenupdate.sh execution_wrongarg -e
./goldenupdate.sh foreign_nestedargs -e
./goldenupdate.sh functions_basic_car -e
./goldenupdate.sh functions_basic_cdr -e
./goldenupdate.sh functions_basic_first -e
./goldenupdate.sh functions_basic_rest -e
./goldenupdate.sh functions_contract_musthavecontentslike -e
./goldenupdate.sh functions_contract_musthavetypeof -e
./goldenupdate.sh functions_environment_bind_returnssymbol -e
./goldenupdate.sh functions_environment_bind_tointeger -e
./goldenupdate.sh functions_environment_isbound -e
./goldenupdate.sh functions_file_import_insidepackage -e
./goldenupdate.sh functions_file_import_invalidpackage -e
./goldenupdate.sh functions_file_import -e
./goldenupdate.sh functions_file_load -e
./goldenupdate.sh functions_file_package -e
./goldenupdate.sh functions_file_save -e
./goldenupdate.sh functions_file_use -e
./goldenupdate.sh functions_log_if_twoarg -e
./goldenupdate.sh functions_logic_if_skipeval -e
./goldenupdate.sh functions_logic_if -e
./goldenupdate.sh functions_logic_not -e
./goldenupdate.sh functions_make_makeexpectation -e
./goldenupdate.sh functions_math_acos -e
./goldenupdate.sh functions_math_asin -e
./goldenupdate.sh functions_math_atan -e
./goldenupdate.sh functions_math_atan2 -e
./goldenupdate.sh functions_math_ceiling -e
./goldenupdate.sh functions_math_cos -e
./goldenupdate.sh functions_math_exp -e
./goldenupdate.sh functions_math_floor -e
./goldenupdate.sh functions_math_lessthan -e
./goldenupdate.sh functions_math_log10 -e
./goldenupdate.sh functions_math_log2 -e
./goldenupdate.sh functions_math_loge -e
./goldenupdate.sh functions_math_minus_negation -e
./goldenupdate.sh functions_math_minus -e
./goldenupdate.sh functions_math_modulo -e
./goldenupdate.sh functions_math_notequal -e
./goldenupdate.sh functions_math_nthroot -e
./goldenupdate.sh functions_math_power -e
./goldenupdate.sh functions_math_sin -e
./goldenupdate.sh functions_math_squareroot -e
./goldenupdate.sh functions_math_tan -e
./goldenupdate.sh functions_math_times -e
./goldenupdate.sh functions_misc_alias -e
./goldenupdate.sh functions_string_length -e
./goldenupdate.sh functions_string_listify -e
./goldenupdate.sh functions_syscalls_applycssstyleto -e
./goldenupdate.sh functions_test_isempty -e
./goldenupdate.sh graphics_closure -e
./goldenupdate.sh graphics_command_hidechildren -e
./goldenupdate.sh graphics_command_vertical -e
./goldenupdate.sh integration_bindanduse -e
./goldenupdate.sh saveload_commands_basic -e
./goldenupdate.sh saveload_error_basic -e
./goldenupdate.sh saveload_error_corruptedfile -e
./goldenupdate.sh saveload_error_filenotfound -e
./goldenupdate.sh saveload_expectation -e
./goldenupdate.sh saveload_float -e
./goldenupdate.sh saveload_integer_zero -e
./goldenupdate.sh saveload_integer -e
./goldenupdate.sh saveload_lambda_basic -e
./goldenupdate.sh saveload_line -e
./goldenupdate.sh saveload_nil -e
./goldenupdate.sh saveload_preservevertical -e
./goldenupdate.sh saveload_separator -e
./goldenupdate.sh saveload_string_basicwithescapes -e
./goldenupdate.sh saveload_symbol_basic -e
./goldenupdate.sh saveload_tag -e
./goldenupdate.sh tags_word_complete -e
./goldenupdate.sh template_basic -e
./goldenupdate.sh template_initializer -e
./goldenupdate.sh template_set_orgmember -e