//startgnumessage//
/*
This file is part of Vodka.

Vodka is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Vodka is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Vodka.  If not, see <https://www.gnu.org/licenses/>.
*/
//endgnumessage//
//testspec// [none]
//testname//  tags_commandtypes_display
//startdescription//
/*
Tests display of tags in commands, lambdas, and expectations, both horizontal and vertical
NOTE ON THIS TEST
I commented out the second part of the test because it was testing step eval,
which is broken and needs to be rewritten from the ground up.
So there may be some weird things in the golden that seem unrelated to this test.
|Shift|~|a|d|d|-|t|a|g|Shift|~|Shift|+|Shift|#|3|Shift|#|3|Shift|Tab|ArrowRight|Shift|$|Shift|Enter|f|o|o|b|a|r|Tab|Enter|Shift|Tab|Shift|Enter|Meta|c|v|Shift| |Shift|&|Backspace|Shift|~|a|d|d|-|t|a|g|Shift|&| |n|Shift|~|Shift|+|Shift|@|n|Shift|@|n|Shift|Tab|Tab|ArrowRight|Shift|$|Shift|Enter|f|o|o|b|a|r|Tab|Enter|Shift|Tab|Shift|Enter|Meta|c|v|Shift| |Shift|~|b|i|n|d|Shift|@|m|Shift|#|3|Shift|Tab|Shift|Enter|Shift|~|Shift|+|Shift|@|m|Shift|@|m|Shift|Tab|Meta|Enter|Enter|Tab|Tab|Meta|c|Shift|Tab|Tab|ArrowRight|Shift|~|a|d|d|-|t|a|g|Tab|Meta|v|ArrowRight|Shift|$|Shift|Enter|f|o|o|b|a|r|Tab|Enter|Shift|Tab|Shift|Enter
*/
//enddescription//
//starttest//
var harness = require('../testharness');
var testactions = [];
testactions.push({type:'keydown',code:'ShiftRight'});
testactions.push({type:'keydown',code:'Backquote'});
testactions.push({type:'keyup',code:'Backquote'});
testactions.push({type:'keyup',code:'ShiftRight'});
testactions.push({type:'keydown',code:'KeyA'});
testactions.push({type:'keyup',code:'KeyA'});
testactions.push({type:'keydown',code:'KeyD'});
testactions.push({type:'keyup',code:'KeyD'});
testactions.push({type:'keydown',code:'KeyD'});
testactions.push({type:'keyup',code:'KeyD'});
testactions.push({type:'keydown',code:'Minus'});
testactions.push({type:'keyup',code:'Minus'});
testactions.push({type:'keydown',code:'KeyT'});
testactions.push({type:'keydown',code:'KeyA'});
testactions.push({type:'keyup',code:'KeyT'});
testactions.push({type:'keyup',code:'KeyA'});
testactions.push({type:'keydown',code:'KeyG'});
testactions.push({type:'keyup',code:'KeyG'});
testactions.push({type:'keydown',code:'ShiftRight'});
testactions.push({type:'keydown',code:'Backquote'});
testactions.push({type:'keyup',code:'Backquote'});
testactions.push({type:'keyup',code:'ShiftRight'});
testactions.push({type:'keydown',code:'ShiftLeft'});
testactions.push({type:'keydown',code:'Equal'});
testactions.push({type:'keyup',code:'Equal'});
testactions.push({type:'keyup',code:'ShiftLeft'});
testactions.push({type:'keydown',code:'ShiftRight'});
testactions.push({type:'keydown',code:'Digit3'});
testactions.push({type:'keyup',code:'ShiftRight'});
testactions.push({type:'keyup',code:'Digit3'});
testactions.push({type:'keydown',code:'Digit3'});
testactions.push({type:'keyup',code:'Digit3'});
testactions.push({type:'keydown',code:'ShiftRight'});
testactions.push({type:'keydown',code:'Digit3'});
testactions.push({type:'keyup',code:'ShiftRight'});
testactions.push({type:'keyup',code:'Digit3'});
testactions.push({type:'keydown',code:'Digit3'});
testactions.push({type:'keyup',code:'Digit3'});
testactions.push({type:'keydown',code:'ShiftRight'});
testactions.push({type:'keydown',code:'Tab'});
testactions.push({type:'keyup',code:'Tab'});
testactions.push({type:'keyup',code:'ShiftRight'});
testactions.push({type:'keydown',code:'ArrowRight'});
testactions.push({type:'keyup',code:'ArrowRight'});
testactions.push({type:'keydown',code:'ShiftRight'});
testactions.push({type:'keydown',code:'Digit4'});
testactions.push({type:'keyup',code:'Digit4'});
testactions.push({type:'keyup',code:'ShiftRight'});
testactions.push({type:'keydown',code:'ShiftLeft'});
testactions.push({type:'keydown',code:'Enter'});
testactions.push({type:'keyup',code:'ShiftLeft'});
testactions.push({type:'keyup',code:'Enter'});
testactions.push({type:'keydown',code:'KeyF'});
testactions.push({type:'keydown',code:'KeyO'});
testactions.push({type:'keyup',code:'KeyF'});
testactions.push({type:'keyup',code:'KeyO'});
testactions.push({type:'keydown',code:'KeyO'});
testactions.push({type:'keydown',code:'KeyB'});
testactions.push({type:'keyup',code:'KeyO'});
testactions.push({type:'keyup',code:'KeyB'});
testactions.push({type:'keydown',code:'KeyA'});
testactions.push({type:'keydown',code:'KeyR'});
testactions.push({type:'keyup',code:'KeyA'});
testactions.push({type:'keyup',code:'KeyR'});
testactions.push({type:'keydown',code:'Tab'});
testactions.push({type:'keyup',code:'Tab'});
testactions.push({type:'keydown',code:'Enter'});
testactions.push({type:'keyup',code:'Enter'});
testactions.push({type:'keydown',code:'ShiftRight'});
testactions.push({type:'keydown',code:'Tab'});
testactions.push({type:'keyup',code:'Tab'});
testactions.push({type:'keyup',code:'ShiftRight'});
testactions.push({type:'keydown',code:'ShiftLeft'});
testactions.push({type:'keydown',code:'Enter'});
testactions.push({type:'keyup',code:'Enter'});
testactions.push({type:'keyup',code:'ShiftLeft'});
testactions.push({type:'keydown',code:'MetaRight'});
testactions.push({type:'keydown',code:'KeyC'});
testactions.push({type:'keydown',code:'KeyV'});
testactions.push({type:'keyup',code:'MetaRight'});
testactions.push({type:'keydown',code:'ShiftLeft'});
testactions.push({type:'keydown',code:'Space'});
testactions.push({type:'keyup',code:'Space'});
testactions.push({type:'keyup',code:'ShiftLeft'});
// testactions.push({type:'keydown',code:'ShiftLeft'});
// testactions.push({type:'keydown',code:'Digit7'});
// testactions.push({type:'keyup',code:'Digit7'});
// testactions.push({type:'keyup',code:'ShiftLeft'});
// testactions.push({type:'keydown',code:'Backspace'});
// testactions.push({type:'keyup',code:'Backspace'});
testactions.push({type:'keydown',code:'ShiftRight'});
testactions.push({type:'keydown',code:'Backquote'});
testactions.push({type:'keyup',code:'Backquote'});
testactions.push({type:'keyup',code:'ShiftRight'});
testactions.push({type:'keydown',code:'KeyA'});
testactions.push({type:'keydown',code:'KeyD'});
testactions.push({type:'keyup',code:'KeyA'});
testactions.push({type:'keyup',code:'KeyD'});
testactions.push({type:'keydown',code:'KeyD'});
testactions.push({type:'keydown',code:'Minus'});
testactions.push({type:'keyup',code:'KeyD'});
testactions.push({type:'keyup',code:'Minus'});
testactions.push({type:'keydown',code:'KeyT'});
testactions.push({type:'keydown',code:'KeyA'});
testactions.push({type:'keyup',code:'KeyT'});
testactions.push({type:'keyup',code:'KeyA'});
testactions.push({type:'keydown',code:'KeyG'});
testactions.push({type:'keyup',code:'KeyG'});
testactions.push({type:'keydown',code:'ShiftLeft'});
testactions.push({type:'keydown',code:'Digit7'});
testactions.push({type:'keyup',code:'Digit7'});
testactions.push({type:'keyup',code:'ShiftLeft'});
testactions.push({type:'keydown',code:'Space'});
testactions.push({type:'keyup',code:'Space'});
testactions.push({type:'keydown',code:'KeyN'});
testactions.push({type:'keyup',code:'KeyN'});
testactions.push({type:'keydown',code:'Enter'});
testactions.push({type:'keyup',code:'Enter'});
testactions.push({type:'keydown',code:'ShiftRight'});
testactions.push({type:'keydown',code:'Backquote'});
testactions.push({type:'keyup',code:'Backquote'});
testactions.push({type:'keyup',code:'ShiftRight'});
testactions.push({type:'keydown',code:'ShiftLeft'});
testactions.push({type:'keydown',code:'Equal'});
testactions.push({type:'keyup',code:'Equal'});
testactions.push({type:'keyup',code:'ShiftLeft'});
testactions.push({type:'keydown',code:'ShiftRight'});
testactions.push({type:'keydown',code:'Digit2'});
testactions.push({type:'keyup',code:'Digit2'});
testactions.push({type:'keyup',code:'ShiftRight'});
testactions.push({type:'keydown',code:'KeyN'});
testactions.push({type:'keyup',code:'KeyN'});
testactions.push({type:'keydown',code:'ShiftRight'});
testactions.push({type:'keydown',code:'Digit2'});
testactions.push({type:'keyup',code:'Digit2'});
testactions.push({type:'keyup',code:'ShiftRight'});
testactions.push({type:'keydown',code:'KeyN'});
testactions.push({type:'keyup',code:'KeyN'});
testactions.push({type:'keydown',code:'ShiftRight'});
testactions.push({type:'keydown',code:'Tab'});
testactions.push({type:'keyup',code:'Tab'});
testactions.push({type:'keydown',code:'Tab'});
testactions.push({type:'keyup',code:'Tab'});
testactions.push({type:'keyup',code:'ShiftRight'});
testactions.push({type:'keydown',code:'ArrowRight'});
testactions.push({type:'keyup',code:'ArrowRight'});
testactions.push({type:'keydown',code:'ShiftRight'});
testactions.push({type:'keydown',code:'Digit4'});
testactions.push({type:'keyup',code:'Digit4'});
testactions.push({type:'keyup',code:'ShiftRight'});
testactions.push({type:'keydown',code:'ShiftLeft'});
testactions.push({type:'keydown',code:'Enter'});
testactions.push({type:'keyup',code:'Enter'});
testactions.push({type:'keyup',code:'ShiftLeft'});
testactions.push({type:'keydown',code:'KeyF'});
testactions.push({type:'keydown',code:'KeyO'});
testactions.push({type:'keyup',code:'KeyF'});
testactions.push({type:'keyup',code:'KeyO'});
testactions.push({type:'keydown',code:'KeyO'});
testactions.push({type:'keydown',code:'KeyB'});
testactions.push({type:'keyup',code:'KeyO'});
testactions.push({type:'keyup',code:'KeyB'});
testactions.push({type:'keydown',code:'KeyA'});
testactions.push({type:'keydown',code:'KeyR'});
testactions.push({type:'keyup',code:'KeyA'});
testactions.push({type:'keyup',code:'KeyR'});
testactions.push({type:'keydown',code:'Tab'});
testactions.push({type:'keyup',code:'Tab'});
testactions.push({type:'keydown',code:'Enter'});
testactions.push({type:'keyup',code:'Enter'});
testactions.push({type:'keydown',code:'ShiftRight'});
testactions.push({type:'keydown',code:'Tab'});
testactions.push({type:'keyup',code:'Tab'});
testactions.push({type:'keyup',code:'ShiftRight'});
testactions.push({type:'keydown',code:'ShiftLeft'});
testactions.push({type:'keydown',code:'Enter'});
testactions.push({type:'keyup',code:'Enter'});
testactions.push({type:'keyup',code:'ShiftLeft'});
testactions.push({type:'keydown',code:'MetaRight'});
testactions.push({type:'keydown',code:'KeyC'});
testactions.push({type:'keydown',code:'KeyV'});
testactions.push({type:'keyup',code:'MetaRight'});
testactions.push({type:'keydown',code:'ShiftLeft'});
testactions.push({type:'keydown',code:'Space'});
testactions.push({type:'keyup',code:'Space'});
testactions.push({type:'keyup',code:'ShiftLeft'});
testactions.push({type:'keydown',code:'ShiftRight'});
testactions.push({type:'keydown',code:'Backquote'});
testactions.push({type:'keyup',code:'Backquote'});
testactions.push({type:'keyup',code:'ShiftRight'});
testactions.push({type:'keydown',code:'KeyB'});
testactions.push({type:'keyup',code:'KeyB'});
testactions.push({type:'keydown',code:'KeyI'});
testactions.push({type:'keyup',code:'KeyI'});
testactions.push({type:'keydown',code:'KeyN'});
testactions.push({type:'keydown',code:'KeyD'});
testactions.push({type:'keyup',code:'KeyN'});
testactions.push({type:'keyup',code:'KeyD'});
testactions.push({type:'keydown',code:'ShiftRight'});
testactions.push({type:'keydown',code:'Digit2'});
testactions.push({type:'keyup',code:'Digit2'});
testactions.push({type:'keyup',code:'ShiftRight'});
testactions.push({type:'keydown',code:'KeyM'});
testactions.push({type:'keyup',code:'KeyM'});
testactions.push({type:'keydown',code:'ShiftRight'});
testactions.push({type:'keydown',code:'Digit3'});
testactions.push({type:'keyup',code:'Digit3'});
testactions.push({type:'keyup',code:'ShiftRight'});
testactions.push({type:'keydown',code:'Digit3'});
testactions.push({type:'keyup',code:'Digit3'});
testactions.push({type:'keydown',code:'ShiftRight'});
testactions.push({type:'keydown',code:'Tab'});
testactions.push({type:'keyup',code:'Tab'});
testactions.push({type:'keyup',code:'ShiftRight'});
testactions.push({type:'keydown',code:'ShiftLeft'});
testactions.push({type:'keydown',code:'Enter'});
testactions.push({type:'keyup',code:'Enter'});
testactions.push({type:'keyup',code:'ShiftLeft'});
testactions.push({type:'keydown',code:'ShiftRight'});
testactions.push({type:'keydown',code:'Backquote'});
testactions.push({type:'keyup',code:'Backquote'});
testactions.push({type:'keyup',code:'ShiftRight'});
testactions.push({type:'keydown',code:'ShiftLeft'});
testactions.push({type:'keydown',code:'Equal'});
testactions.push({type:'keyup',code:'Equal'});
testactions.push({type:'keyup',code:'ShiftLeft'});
testactions.push({type:'keydown',code:'ShiftRight'});
testactions.push({type:'keydown',code:'Digit2'});
testactions.push({type:'keyup',code:'ShiftRight'});
testactions.push({type:'keyup',code:'Digit2'});
testactions.push({type:'keydown',code:'KeyM'});
testactions.push({type:'keyup',code:'KeyM'});
testactions.push({type:'keydown',code:'ShiftRight'});
testactions.push({type:'keydown',code:'Digit2'});
testactions.push({type:'keyup',code:'ShiftRight'});
testactions.push({type:'keyup',code:'Digit2'});
testactions.push({type:'keydown',code:'KeyM'});
testactions.push({type:'keyup',code:'KeyM'});
testactions.push({type:'keydown',code:'ShiftRight'});
testactions.push({type:'keydown',code:'Tab'});
testactions.push({type:'keyup',code:'Tab'});
testactions.push({type:'keyup',code:'ShiftRight'});
// testactions.push({type:'keydown',code:'MetaLeft'});
// testactions.push({type:'keydown',code:'Enter'});
// testactions.push({type:'keydown',code:'Enter'});
// testactions.push({type:'keyup',code:'MetaLeft'});
// testactions.push({type:'keydown',code:'Tab'});
// testactions.push({type:'keyup',code:'Tab'});
// testactions.push({type:'keydown',code:'Tab'});
// testactions.push({type:'keyup',code:'Tab'});
// testactions.push({type:'keydown',code:'MetaRight'});
// testactions.push({type:'keydown',code:'KeyC'});
// testactions.push({type:'keyup',code:'MetaRight'});
// testactions.push({type:'keydown',code:'ShiftRight'});
// testactions.push({type:'keydown',code:'Tab'});
// testactions.push({type:'keyup',code:'Tab'});
// testactions.push({type:'keydown',code:'Tab'});
// testactions.push({type:'keyup',code:'Tab'});
// testactions.push({type:'keyup',code:'ShiftRight'});
// testactions.push({type:'keydown',code:'ArrowRight'});
// testactions.push({type:'keyup',code:'ArrowRight'});
// testactions.push({type:'keydown',code:'ShiftRight'});
// testactions.push({type:'keydown',code:'Backquote'});
// testactions.push({type:'keyup',code:'Backquote'});
// testactions.push({type:'keyup',code:'ShiftRight'});
// testactions.push({type:'keydown',code:'KeyA'});
// testactions.push({type:'keyup',code:'KeyA'});
// testactions.push({type:'keydown',code:'KeyD'});
// testactions.push({type:'keyup',code:'KeyD'});
// testactions.push({type:'keydown',code:'KeyD'});
// testactions.push({type:'keyup',code:'KeyD'});
// testactions.push({type:'keydown',code:'Minus'});
// testactions.push({type:'keyup',code:'Minus'});
// testactions.push({type:'keydown',code:'KeyT'});
// testactions.push({type:'keyup',code:'KeyT'});
// testactions.push({type:'keydown',code:'KeyA'});
// testactions.push({type:'keyup',code:'KeyA'});
// testactions.push({type:'keydown',code:'KeyG'});
// testactions.push({type:'keyup',code:'KeyG'});
// testactions.push({type:'keydown',code:'Tab'});
// testactions.push({type:'keyup',code:'Tab'});
// testactions.push({type:'keydown',code:'MetaRight'});
// testactions.push({type:'keydown',code:'KeyV'});
// testactions.push({type:'keyup',code:'MetaRight'});
// testactions.push({type:'keydown',code:'ArrowRight'});
// testactions.push({type:'keyup',code:'ArrowRight'});
// testactions.push({type:'keydown',code:'ShiftRight'});
// testactions.push({type:'keydown',code:'Digit4'});
// testactions.push({type:'keyup',code:'Digit4'});
// testactions.push({type:'keyup',code:'ShiftRight'});
// testactions.push({type:'keydown',code:'ShiftLeft'});
// testactions.push({type:'keydown',code:'Enter'});
// testactions.push({type:'keyup',code:'ShiftLeft'});
// testactions.push({type:'keyup',code:'Enter'});
// testactions.push({type:'keydown',code:'KeyF'});
// testactions.push({type:'keyup',code:'KeyF'});
// testactions.push({type:'keydown',code:'KeyO'});
// testactions.push({type:'keyup',code:'KeyO'});
// testactions.push({type:'keydown',code:'KeyO'});
// testactions.push({type:'keyup',code:'KeyO'});
// testactions.push({type:'keydown',code:'KeyB'});
// testactions.push({type:'keyup',code:'KeyB'});
// testactions.push({type:'keydown',code:'KeyA'});
// testactions.push({type:'keyup',code:'KeyA'});
// testactions.push({type:'keydown',code:'KeyR'});
// testactions.push({type:'keyup',code:'KeyR'});
// testactions.push({type:'keydown',code:'Tab'});
// testactions.push({type:'keyup',code:'Tab'});
// testactions.push({type:'keydown',code:'Enter'});
// testactions.push({type:'keyup',code:'Enter'});
// testactions.push({type:'keydown',code:'ShiftRight'});
// testactions.push({type:'keydown',code:'Tab'});
// testactions.push({type:'keyup',code:'Tab'});
// testactions.push({type:'keyup',code:'ShiftRight'});
// testactions.push({type:'keydown',code:'ShiftLeft'});
// testactions.push({type:'keydown',code:'Enter'});
// testactions.push({type:'keyup',code:'Enter'});
// testactions.push({type:'keyup',code:'ShiftLeft'});
harness.runTest(testactions, 'direct');
//endtest//
